/**
 * OpenAI Codex integration helpers.
 *
 * Codex natively discovers AGENTS.md (and AGENTS.override.md) from the project
 * root down to cwd, plus optional fallback filenames from config.toml.
 * Default combined budget: project_doc_max_bytes = 32 KiB.
 *
 * @see https://developers.openai.com/codex/guides/agents-md
 */

import { managedRegion } from "./fsutil.mjs";

const KIBIBYTE_BYTES = 1024;
const CODEX_DEFAULT_MAX_KIBIBYTES = 32;
const BUDGET_WARNING_RATIO = 0.85;
const BUDGET_HEADROOM_MULTIPLIER = 1.5;
const CODEX_MANAGED_KEYS = Object.freeze([
  "project_doc_max_bytes",
  "project_doc_fallback_filenames",
]);
const TOML_KEY_SEGMENT = String.raw`(?:[A-Za-z0-9_-]+|"[^"]+"|'[^']+')`;
const TOML_TABLE_HEADER = new RegExp(
  String.raw`^\[{1,2}\s*${TOML_KEY_SEGMENT}(?:\s*\.\s*${TOML_KEY_SEGMENT})*\s*\]{1,2}\s*(?:#.*)?$`,
);
const TOML_MULTILINE_DELIMITERS = Object.freeze(['"""', "'''"]);

export const CODEX_ROOT_AGENTS = "AGENTS.md";
export const CODEX_OVERRIDE = "AGENTS.override.md";
export const CODEX_CONFIG_PATH = ".codex/config.toml";
/** Codex default project_doc_max_bytes */
export const CODEX_DEFAULT_MAX_BYTES =
  CODEX_DEFAULT_MAX_KIBIBYTES * KIBIBYTE_BYTES;

export const TOML_MANAGED_START = "# agent-sync:start";
export const TOML_MANAGED_END = "# agent-sync:end";
export const TOML_MANAGED_BANNER =
  "# Generated by agent-sync. Edit AGENTS.md, then run: agent-sync apply";

/** Filenames Codex should also try when AGENTS.md is missing (per-directory). */
export const CODEX_FALLBACK_CANDIDATES = Object.freeze([
  "CLAUDE.md",
  "GEMINI.md",
  "CONVENTIONS.md",
  ".cursorrules",
  ".clinerules",
  ".windsurfrules",
  ".github/copilot-instructions.md",
]);

/**
 * Build fallback list from enabled targets + well-known names.
 * Never includes AGENTS.md itself (Codex already checks it first).
 */
export function buildCodexFallbacks(config, targets) {
  const set = new Set();
  for (const t of targets) {
    if (!config.targets?.[t.id]) continue;
    if (t.id === "codex" || t.id === "codex-agents") continue;
    if (t.path && t.path !== CODEX_ROOT_AGENTS && !t.path.endsWith(".toml")) {
      // Keep target names deterministic across operating systems.
      set.add(t.path.replace(/\\/g, "/"));
    }
  }
  for (const name of CODEX_FALLBACK_CANDIDATES) set.add(name);
  // Prefer stable order
  return [...set].sort();
}

/**
 * Render managed .codex/config.toml fragment for project-local Codex settings.
 * Safe to merge into an existing user config.toml via markers.
 */
export function renderCodexConfigToml({
  sourceRel,
  fallbacks = [],
  maxBytes = CODEX_DEFAULT_MAX_BYTES,
  sourceBytes = 0,
} = {}) {
  // If source alone exceeds default budget, bump the limit with headroom.
  let projectDocMax = maxBytes;
  if (sourceBytes > 0 && sourceBytes > maxBytes * BUDGET_WARNING_RATIO) {
    projectDocMax = Math.max(
      maxBytes,
      Math.ceil(sourceBytes * BUDGET_HEADROOM_MULTIPLIER),
    );
  }

  const fallbackLiteral =
    fallbacks.length === 0
      ? "[]"
      : `[\n${fallbacks.map((name) => `  ${JSON.stringify(name)}`).join(",\n")},\n]`;
  const sourceLabel = String(sourceRel || "AGENTS.md").replace(/[\r\n]+/g, " ");

  const lines = [
    TOML_MANAGED_BANNER,
    TOML_MANAGED_START,
    `# Codex project instructions - source of truth: ${sourceLabel}`,
    `# Discovery order per dir: AGENTS.override.md -> AGENTS.md -> fallbacks below`,
    `# Docs: https://developers.openai.com/codex/guides/agents-md`,
    ``,
    `project_doc_max_bytes = ${projectDocMax}`,
    `project_doc_fallback_filenames = ${fallbackLiteral}`,
    TOML_MANAGED_END,
    ``,
  ];
  return lines.join("\n");
}

/**
 * Validate source content against Codex constraints.
 * @returns {{ ok: boolean, errors: string[], warnings: string[], bytes: number }}
 */
export function validateCodexSource(content, { maxBytes = CODEX_DEFAULT_MAX_BYTES } = {}) {
  const text = content || "";
  const bytes = Buffer.byteLength(text, "utf8");
  const errors = [];
  const warnings = [];
  const budgetKind =
    maxBytes === CODEX_DEFAULT_MAX_BYTES ? "default Codex budget" : "configured Codex budget";

  if (!text.trim()) {
    errors.push("AGENTS.md is empty — Codex ignores empty instruction files");
  }
  if (bytes > maxBytes) {
    warnings.push(
      `source is ${bytes} bytes (> ${budgetKind} ${maxBytes}). ` +
        `agent-sync will raise project_doc_max_bytes in .codex/config.toml; ` +
        `or split guidance into nested AGENTS.md files.`,
    );
  } else if (bytes > maxBytes * BUDGET_WARNING_RATIO) {
    warnings.push(
      `source is ${bytes} bytes (near ${budgetKind} ${maxBytes}). Consider trimming or nesting.`,
    );
  }

  return { ok: errors.length === 0, errors, warnings, bytes };
}

export function isRootAgentsPath(sourceRel, { platform = process.platform } = {}) {
  const n = (sourceRel || "").replace(/\\/g, "/").replace(/^\.\//, "");
  return platform === "win32"
    ? n.toLowerCase() === CODEX_ROOT_AGENTS.toLowerCase()
    : n === CODEX_ROOT_AGENTS;
}

function tomlManagedSection(managedBlock, markers) {
  const region = managedRegion(managedBlock, markers);
  if (!region) throw new Error("Rendered TOML is missing agent-sync managed markers.");
  const inner = managedBlock
    .slice(region.start, region.end + markers.end.length)
    .trim();
  return managedBlock.includes(TOML_MANAGED_BANNER)
    ? `${TOML_MANAGED_BANNER}\n${inner}`
    : inner;
}

function stripTrailingTomlBanner(prefix) {
  const trimmed = prefix.trimEnd();
  if (!trimmed.endsWith(TOML_MANAGED_BANNER)) return trimmed;
  const bannerStart = trimmed.length - TOML_MANAGED_BANNER.length;
  if (bannerStart > 0 && trimmed[bannerStart - 1] !== "\n") return trimmed;
  return trimmed.slice(0, bannerStart).trimEnd();
}

function tokenCount(content, token) {
  return content.split(token).length - 1;
}

function openedMultilineDelimiter(line) {
  const commentStart = line.indexOf("#");
  const code = commentStart === -1 ? line : line.slice(0, commentStart);
  return TOML_MULTILINE_DELIMITERS.find((token) => tokenCount(code, token) % 2 === 1) || null;
}

function managedKeysOnLine(line) {
  return CODEX_MANAGED_KEYS.filter((key) => {
    const pattern = new RegExp(`^["']?${key}["']?\\s*=`);
    return pattern.test(line);
  });
}

function rootManagedKeys(content) {
  const conflicts = [];
  let atRoot = true;
  let multilineDelimiter = null;
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (multilineDelimiter) {
      if (tokenCount(line, multilineDelimiter) % 2 === 1) multilineDelimiter = null;
      continue;
    }
    if (!trimmed || trimmed.startsWith("#")) continue;
    if (atRoot) conflicts.push(...managedKeysOnLine(trimmed));
    multilineDelimiter = openedMultilineDelimiter(line);
    if (!multilineDelimiter && TOML_TABLE_HEADER.test(trimmed)) atRoot = false;
  }
  return [...new Set(conflicts)];
}

function assertNoManagedKeyConflicts(content) {
  const conflicts = rootManagedKeys(content);
  if (conflicts.length === 0) return;
  throw new Error(
    `Existing Codex config defines agent-sync managed key(s): ${conflicts.join(", ")}. ` +
      "Remove them before applying so the TOML remains valid.",
  );
}

function combineManagedAndUserToml(managedBlock, userContent) {
  assertNoManagedKeyConflicts(userContent);
  const chunks = [managedBlock.trim(), userContent.trim()].filter(Boolean);
  return `${chunks.join("\n\n")}\n`;
}

export function mergeUnmanagedToml(existing, managedBlock) {
  const markers = { start: TOML_MANAGED_START, end: TOML_MANAGED_END };
  if (!managedRegion(managedBlock, markers)) {
    throw new Error("Rendered TOML is missing agent-sync managed markers.");
  }
  return combineManagedAndUserToml(managedBlock, existing);
}

/**
 * Merge TOML managed region (same semantics as HTML markers).
 */
export function mergeTomlManaged(existing, managedBlock) {
  const markers = { start: TOML_MANAGED_START, end: TOML_MANAGED_END };
  if (!managedRegion(managedBlock, markers)) {
    throw new Error("Rendered TOML is missing agent-sync managed markers.");
  }
  const region = managedRegion(existing, markers);
  if (!region) {
    return managedBlock.endsWith("\n") ? managedBlock : managedBlock + "\n";
  }

  const before = stripTrailingTomlBanner(existing.slice(0, region.start));
  const after = existing
    .slice(region.end + TOML_MANAGED_END.length)
    .replace(/^\s*/, "");

  const userContent = [before, after].filter((chunk) => chunk.trim()).join("\n\n");
  return combineManagedAndUserToml(
    tomlManagedSection(managedBlock, markers),
    userContent,
  );
}
