/**
 * OpenAI Codex integration helpers.
 *
 * Codex natively discovers AGENTS.md (and AGENTS.override.md) from the project
 * root down to cwd, plus optional fallback filenames from config.toml.
 * Default combined budget: project_doc_max_bytes = 32 KiB.
 *
 * @see https://developers.openai.com/codex/guides/agents-md
 */

export const CODEX_ROOT_AGENTS = "AGENTS.md";
export const CODEX_OVERRIDE = "AGENTS.override.md";
export const CODEX_CONFIG_PATH = ".codex/config.toml";
/** Codex default project_doc_max_bytes */
export const CODEX_DEFAULT_MAX_BYTES = 32 * 1024;

export const TOML_MANAGED_START = "# agent-sync:start";
export const TOML_MANAGED_END = "# agent-sync:end";
export const TOML_MANAGED_BANNER =
  "# Generated by agent-sync. Edit AGENTS.md, then run: agent-sync apply";

/** Filenames Codex should also try when AGENTS.md is missing (per-directory). */
export const CODEX_FALLBACK_CANDIDATES = [
  "CLAUDE.md",
  "GEMINI.md",
  "CONVENTIONS.md",
  ".cursorrules",
  ".clinerules",
  ".windsurfrules",
  ".github/copilot-instructions.md",
];

/**
 * Build fallback list from enabled targets + well-known names.
 * Never includes AGENTS.md itself (Codex already checks it first).
 */
export function buildCodexFallbacks(config, targets) {
  const set = new Set();
  for (const t of targets) {
    if (!config.targets?.[t.id]) continue;
    if (t.id === "codex" || t.id === "codex-agents") continue;
    if (t.path && t.path !== CODEX_ROOT_AGENTS && !t.path.endsWith(".toml")) {
      // Codex only looks at basenames in each directory for fallbacks —
      // nested paths like .github/copilot-instructions.md still work as
      // explicit fallback names in recent Codex (listed as filename strings).
      set.add(t.path.replace(/\\/g, "/"));
    }
  }
  for (const name of CODEX_FALLBACK_CANDIDATES) set.add(name);
  // Prefer stable order
  return [...set].sort((a, b) => a.localeCompare(b));
}

/**
 * Render managed .codex/config.toml fragment for project-local Codex settings.
 * Safe to merge into an existing user config.toml via markers.
 */
export function renderCodexConfigToml({
  sourceRel,
  fallbacks = [],
  maxBytes = CODEX_DEFAULT_MAX_BYTES,
  sourceBytes = 0,
} = {}) {
  // If source alone exceeds default budget, bump the limit with headroom.
  let projectDocMax = maxBytes;
  if (sourceBytes > 0 && sourceBytes > maxBytes * 0.85) {
    projectDocMax = Math.max(maxBytes, Math.ceil(sourceBytes * 1.5));
  }

  const fallbackLiteral =
    fallbacks.length === 0
      ? "[]"
      : `[\n${fallbacks.map((f) => `  "${f.replace(/"/g, '\\"')}"`).join(",\n")},\n]`;

  const lines = [
    TOML_MANAGED_BANNER,
    TOML_MANAGED_START,
    `# Codex project instructions - source of truth: ${sourceRel}`,
    `# Discovery order per dir: AGENTS.override.md -> AGENTS.md -> fallbacks below`,
    `# Docs: https://developers.openai.com/codex/guides/agents-md`,
    ``,
    `project_doc_max_bytes = ${projectDocMax}`,
    `project_doc_fallback_filenames = ${fallbackLiteral}`,
    TOML_MANAGED_END,
    ``,
  ];
  return lines.join("\n");
}

/**
 * Validate source content against Codex constraints.
 * @returns {{ ok: boolean, errors: string[], warnings: string[], bytes: number }}
 */
export function validateCodexSource(content, { maxBytes = CODEX_DEFAULT_MAX_BYTES } = {}) {
  const text = content || "";
  const bytes = Buffer.byteLength(text, "utf8");
  const errors = [];
  const warnings = [];

  if (!text.trim()) {
    errors.push("AGENTS.md is empty — Codex ignores empty instruction files");
  }
  if (bytes > maxBytes) {
    warnings.push(
      `source is ${bytes} bytes (> default Codex budget ${maxBytes}). ` +
        `agent-sync will raise project_doc_max_bytes in .codex/config.toml; ` +
        `or split guidance into nested AGENTS.md files.`,
    );
  } else if (bytes > maxBytes * 0.85) {
    warnings.push(
      `source is ${bytes} bytes (near Codex default ${maxBytes} budget). Consider trimming or nesting.`,
    );
  }

  return { ok: errors.length === 0, errors, warnings, bytes };
}

export function isRootAgentsPath(sourceRel) {
  const n = (sourceRel || "").replace(/\\/g, "/").replace(/^\.\//, "");
  return n === CODEX_ROOT_AGENTS || n.toLowerCase() === "agents.md";
}

/**
 * Merge TOML managed region (same semantics as HTML markers).
 */
export function mergeTomlManaged(existing, managedBlock) {
  if (!existing || !existing.includes(TOML_MANAGED_START)) {
    return managedBlock.endsWith("\n") ? managedBlock : managedBlock + "\n";
  }
  const start = existing.indexOf(TOML_MANAGED_START);
  const end = existing.indexOf(TOML_MANAGED_END);
  if (start === -1 || end === -1 || end < start) {
    return managedBlock.endsWith("\n") ? managedBlock : managedBlock + "\n";
  }

  let before = existing.slice(0, start);
  before = before.replace(TOML_MANAGED_BANNER, "").replace(/\s*$/, "");
  let after = existing.slice(end + TOML_MANAGED_END.length).replace(/^\s*/, "");

  if (!before.trim() && !after.trim()) {
    return managedBlock.endsWith("\n") ? managedBlock : managedBlock + "\n";
  }

  const innerStart = managedBlock.indexOf(TOML_MANAGED_START);
  const innerEnd = managedBlock.indexOf(TOML_MANAGED_END);
  const managedInner =
    innerStart !== -1 && innerEnd !== -1
      ? managedBlock.slice(innerStart, innerEnd + TOML_MANAGED_END.length).trim()
      : managedBlock.trim();

  const managedSection = managedBlock.includes(TOML_MANAGED_BANNER)
    ? `${TOML_MANAGED_BANNER}\n${managedInner}`
    : managedInner;

  const chunks = [];
  if (before.trim()) chunks.push(before.trimEnd());
  chunks.push(managedSection);
  if (after.trim()) chunks.push(after.trim());
  return chunks.join("\n\n") + "\n";
}
