import {
  TOML_MANAGED_START,
  TOML_MANAGED_END,
  TOML_MANAGED_BANNER,
  mergeTomlManaged,
  mergeUnmanagedToml,
} from "./codex.mjs";
import { managedRegion } from "./fsutil.mjs";

export const MANAGED_START = "<!-- agent-sync:start -->";
export const MANAGED_END = "<!-- agent-sync:end -->";
export const MANAGED_BANNER =
  "<!-- Generated by agent-sync. Edit AGENTS.md, then run: agent-sync apply -->";

export function markersFor(target) {
  if (target?.format === "toml") {
    return {
      start: TOML_MANAGED_START,
      end: TOML_MANAGED_END,
      banner: TOML_MANAGED_BANNER,
      merge: mergeTomlManaged,
      mergeUnmanaged: mergeUnmanagedToml,
    };
  }
  return {
    start: MANAGED_START,
    end: MANAGED_END,
    banner: MANAGED_BANNER,
    merge: mergeManagedContent,
  };
}

export function wrapManaged(body) {
  return [MANAGED_BANNER, MANAGED_START, "", body.trim(), "", MANAGED_END, ""].join(
    "\n",
  );
}

function managedSection(managedBlock, markerSet) {
  const region = managedRegion(managedBlock, markerSet);
  if (!region) throw new Error("Rendered content is missing agent-sync managed markers.");
  const inner = managedBlock
    .slice(region.start, region.end + markerSet.end.length)
    .trim();
  return managedBlock.includes(markerSet.banner)
    ? `${markerSet.banner}\n${inner}`
    : inner;
}

function stripTrailingBanner(prefix, banner) {
  const trimmed = prefix.trimEnd();
  if (!trimmed.endsWith(banner)) return trimmed;
  const bannerStart = trimmed.length - banner.length;
  if (bannerStart > 0 && trimmed[bannerStart - 1] !== "\n") return trimmed;
  return trimmed.slice(0, bannerStart).trimEnd();
}

function resolvedMarkers(markerSet) {
  return {
    start: markerSet.start || MANAGED_START,
    end: markerSet.end || MANAGED_END,
    banner: markerSet.banner || MANAGED_BANNER,
  };
}

function withTrailingNewline(content) {
  return content.endsWith("\n") ? content : `${content}\n`;
}

function outsideManagedRegion(existing, region, markers) {
  return {
    before: stripTrailingBanner(existing.slice(0, region.start), markers.banner),
    after: existing.slice(region.end + markers.end.length).trimStart(),
  };
}

function hasUserNotes({ before, after }) {
  return Boolean(before.trim() || after.trim());
}

function combineManagedContent({ before, after }, managedBlock, markers) {
  const chunks = [];
  if (before.trim()) chunks.push(before);
  chunks.push(managedSection(managedBlock, markers));
  if (after.trim()) chunks.push(after.trim());
  return `${chunks.join("\n\n")}\n`;
}

export function mergeManagedContent(existing, managedBlock, markerSet = {}) {
  const markers = resolvedMarkers(markerSet);
  if (!managedRegion(managedBlock, markers)) {
    throw new Error("Rendered content is missing agent-sync managed markers.");
  }
  const normalizedBlock = withTrailingNewline(managedBlock);
  const region = managedRegion(existing, markers);
  if (!region) return normalizedBlock;

  const outside = outsideManagedRegion(existing, region, markers);
  if (!hasUserNotes(outside)) return normalizedBlock;
  return combineManagedContent(outside, managedBlock, markers);
}

export function extractManagedBody(content, markerSet = {}) {
  const markers = {
    start: markerSet.start || MANAGED_START,
    end: markerSet.end || MANAGED_END,
  };
  const region = managedRegion(content, markers);
  if (!region) return null;
  return content.slice(region.start + markers.start.length, region.end).trim();
}

export {
  TOML_MANAGED_START,
  TOML_MANAGED_END,
  TOML_MANAGED_BANNER,
  mergeTomlManaged,
  mergeUnmanagedToml,
};
