/**
 * Target adapters: how each coding agent expects project instructions.
 *
 * Modes:
 * - import: thin pointer/wrapper that references AGENTS.md (preferred)
 * - copy: full content with managed markers (for tools that only read their own file)
 * - link: filesystem symlink/junction to AGENTS.md
 */

import {
  CODEX_CONFIG_PATH,
  CODEX_ROOT_AGENTS,
  buildCodexFallbacks,
  renderCodexConfigToml,
  TOML_MANAGED_START,
  TOML_MANAGED_END,
  TOML_MANAGED_BANNER,
  mergeTomlManaged,
  isRootAgentsPath,
} from "./codex.mjs";

export const MANAGED_START = "<!-- agent-sync:start -->";
export const MANAGED_END = "<!-- agent-sync:end -->";
export const MANAGED_BANNER =
  "<!-- Generated by agent-sync. Edit AGENTS.md, then run: agent-sync apply -->";

/**
 * @typedef {'import' | 'copy' | 'link'} SyncMode
 * @typedef {'markdown' | 'toml'} TargetFormat
 * @typedef {object} TargetDef
 * @property {string} id
 * @property {string} name
 * @property {string} path
 * @property {boolean} defaultEnabled
 * @property {SyncMode} preferredMode
 * @property {SyncMode[]} supportedModes
 * @property {string} description
 * @property {TargetFormat} [format]
 * @property {boolean} [dynamic] - needs full config + target list at render time
 * @property {(ctx: RenderContext) => string} renderImport
 * @property {(ctx: RenderContext) => string} renderCopy
 * @property {(ctx: RenderContext) => boolean} [shouldEmit]
 *
 * @typedef {object} RenderContext
 * @property {string} sourceRel
 * @property {string} sourceContent
 * @property {string} [projectName]
 * @property {object} [config]
 * @property {TargetDef[]} [allTargets]
 */

/** @type {TargetDef[]} */
export const TARGETS = [
  {
    id: "codex",
    name: "OpenAI Codex",
    path: CODEX_CONFIG_PATH,
    defaultEnabled: true,
    preferredMode: "copy",
    supportedModes: ["copy"],
    format: "toml",
    dynamic: true,
    description:
      "Codex project config (.codex/config.toml): fallback filenames + doc size budget. Native instructions stay in AGENTS.md.",
    renderImport: (ctx) => renderCodexTarget(ctx),
    renderCopy: (ctx) => renderCodexTarget(ctx),
  },
  {
    id: "codex-agents",
    name: "OpenAI Codex (root AGENTS.md)",
    path: CODEX_ROOT_AGENTS,
    defaultEnabled: true,
    preferredMode: "copy",
    supportedModes: ["copy", "link"],
    dynamic: true,
    description:
      "Ensures root AGENTS.md exists for Codex when your source file lives elsewhere. Skipped when source is already AGENTS.md.",
    // Placeholder — real skip/render decided in sync.mjs via shouldEmit()
    renderImport: ({ sourceContent }) =>
      sourceContent.endsWith("\n") ? sourceContent : sourceContent + "\n",
    renderCopy: ({ sourceContent }) =>
      sourceContent.endsWith("\n") ? sourceContent : sourceContent + "\n",
    shouldEmit: (ctx) => !isRootAgentsPath(ctx.sourceRel),
  },
  {
    id: "claude",
    name: "Claude Code",
    path: "CLAUDE.md",
    defaultEnabled: true,
    preferredMode: "import",
    supportedModes: ["import", "copy", "link"],
    description: "Claude Code project memory (does not natively read AGENTS.md)",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Claude Code`,
          ``,
          `This project uses [\`AGENTS.md\`](${sourceRel}) as the single source of truth for coding-agent instructions.`,
          ``,
          `Claude Code: follow @${sourceRel} for all project conventions, commands, and constraints.`,
          ``,
          `Do not maintain separate rules here - update \`${sourceRel}\` instead, then run \`agent-sync apply\`.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Claude Code`,
          ``,
          `> Synced from \`${sourceRel}\`. Prefer editing that file.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    path: ".github/copilot-instructions.md",
    defaultEnabled: true,
    preferredMode: "copy",
    supportedModes: ["import", "copy", "link"],
    description: "GitHub Copilot custom instructions",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# GitHub Copilot instructions`,
          ``,
          `Follow the repository file \`${sourceRel}\` as the primary source of coding-agent guidance.`,
          `Mirror its commands, conventions, and constraints for all suggestions and agent edits.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# GitHub Copilot instructions`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "cursor-legacy",
    name: "Cursor (.cursorrules)",
    path: ".cursorrules",
    defaultEnabled: false,
    preferredMode: "copy",
    supportedModes: ["import", "copy", "link"],
    description: "Legacy Cursor rules file (deprecated but still read)",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Cursor rules`,
          ``,
          `Use \`${sourceRel}\` as the project instruction source.`,
          `Follow every section in that file for builds, tests, style, and boundaries.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Cursor rules`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "cursor-rules",
    name: "Cursor rules (MDC)",
    path: ".cursor/rules/agents.mdc",
    defaultEnabled: true,
    preferredMode: "copy",
    supportedModes: ["import", "copy"],
    description: "Modern Cursor project rule (.mdc with alwaysApply)",
    renderImport: ({ sourceRel }) =>
      [
        `---`,
        `description: Project agent instructions (synced from AGENTS.md)`,
        `alwaysApply: true`,
        `---`,
        ``,
        MANAGED_BANNER,
        MANAGED_START,
        ``,
        `Follow \`${sourceRel}\` as the single source of truth for this repository.`,
        `Apply its toolchain commands, conventions, and judgment boundaries to every task.`,
        ``,
        MANAGED_END,
        ``,
      ].join("\n"),
    renderCopy: ({ sourceContent, sourceRel }) =>
      [
        `---`,
        `description: Project agent instructions (synced from AGENTS.md)`,
        `alwaysApply: true`,
        `---`,
        ``,
        MANAGED_BANNER,
        MANAGED_START,
        ``,
        `> Synced from \`${sourceRel}\`.`,
        ``,
        sourceContent.trim(),
        ``,
        MANAGED_END,
        ``,
      ].join("\n"),
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    path: "GEMINI.md",
    defaultEnabled: false,
    preferredMode: "import",
    supportedModes: ["import", "copy", "link"],
    description: "Google Gemini CLI project context",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Gemini CLI`,
          ``,
          `Project instructions live in \`${sourceRel}\`. Read and follow that file for all coding tasks.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Gemini CLI`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "windsurf",
    name: "Windsurf",
    path: ".windsurfrules",
    defaultEnabled: false,
    preferredMode: "copy",
    supportedModes: ["import", "copy", "link"],
    description: "Windsurf / Codeium rules",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Windsurf rules`,
          ``,
          `Follow \`${sourceRel}\` for project conventions and commands.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Windsurf rules`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "aider",
    name: "Aider",
    path: "CONVENTIONS.md",
    defaultEnabled: false,
    preferredMode: "copy",
    supportedModes: ["import", "copy", "link"],
    description: "Aider project conventions file",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Aider conventions`,
          ``,
          `See \`${sourceRel}\` for the full project agent guide.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Aider conventions`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "cline",
    name: "Cline / Roo",
    path: ".clinerules",
    defaultEnabled: false,
    preferredMode: "copy",
    supportedModes: ["import", "copy", "link"],
    description: "Cline / Roo-style project rules",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Cline rules`,
          ``,
          `Primary instructions: \`${sourceRel}\`. Follow that file completely.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Cline rules`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
  {
    id: "continue",
    name: "Continue",
    path: ".continue/rules/agents.md",
    defaultEnabled: false,
    preferredMode: "copy",
    supportedModes: ["import", "copy"],
    description: "Continue.dev project rules",
    renderImport: ({ sourceRel }) =>
      wrapManaged(
        [
          `# Continue rules`,
          ``,
          `Use \`${sourceRel}\` as the project instruction source.`,
        ].join("\n"),
      ),
    renderCopy: ({ sourceContent, sourceRel }) =>
      wrapManaged(
        [
          `# Continue rules`,
          ``,
          `> Synced from \`${sourceRel}\` by agent-sync.`,
          ``,
          sourceContent.trim(),
        ].join("\n"),
      ),
  },
];

function renderCodexTarget(ctx) {
  const fallbacks = buildCodexFallbacks(ctx.config || { targets: {} }, ctx.allTargets || TARGETS);
  const sourceBytes = Buffer.byteLength(ctx.sourceContent || "", "utf8");
  return renderCodexConfigToml({
    sourceRel: ctx.sourceRel,
    fallbacks,
    sourceBytes,
  });
}

export function getTarget(id) {
  return TARGETS.find((t) => t.id === id);
}

export function markersFor(target) {
  if (target?.format === "toml") {
    return {
      start: TOML_MANAGED_START,
      end: TOML_MANAGED_END,
      banner: TOML_MANAGED_BANNER,
      merge: mergeTomlManaged,
    };
  }
  return {
    start: MANAGED_START,
    end: MANAGED_END,
    banner: MANAGED_BANNER,
    merge: mergeManagedContent,
  };
}

export function wrapManaged(body) {
  return [MANAGED_BANNER, MANAGED_START, "", body.trim(), "", MANAGED_END, ""].join(
    "\n",
  );
}

/**
 * Replace managed region in an existing file, or return full managed content.
 * Preserves any user content outside the markers (and outside the banner).
 */
export function mergeManagedContent(existing, managedBlock, markerSet) {
  const startTag = markerSet?.start || MANAGED_START;
  const endTag = markerSet?.end || MANAGED_END;
  const banner = markerSet?.banner || MANAGED_BANNER;

  if (!existing || !existing.includes(startTag)) {
    return managedBlock;
  }
  const start = existing.indexOf(startTag);
  const end = existing.indexOf(endTag);
  if (start === -1 || end === -1 || end < start) {
    return managedBlock;
  }

  // Strip trailing whitespace / old banner from the prefix so we don't duplicate it.
  let before = existing.slice(0, start);
  before = before.replaceAll(banner, "");
  before = before.replace(/\s*$/, "");

  let after = existing.slice(end + endTag.length);
  after = after.replace(/^\s*/, "");

  // If nothing user-owned remains outside the managed block, replace wholesale.
  // This keeps re-apply idempotent for fully-generated targets.
  if (!before.trim() && !after.trim()) {
    return managedBlock.endsWith("\n") ? managedBlock : managedBlock + "\n";
  }

  const innerStart = managedBlock.indexOf(startTag);
  const innerEnd = managedBlock.indexOf(endTag);
  if (innerStart === -1 || innerEnd === -1) {
    const parts = [before, managedBlock.trim(), after].filter((p) => p && p.length);
    return parts.join("\n\n") + "\n";
  }

  const managedInner = managedBlock
    .slice(innerStart, innerEnd + endTag.length)
    .trim();
  // Keep banner immediately above the start marker (single newline), matching renderers.
  const managedSection = managedBlock.includes(banner)
    ? `${banner}\n${managedInner}`
    : managedInner;

  const chunks = [];
  if (before.trim()) chunks.push(before.trimEnd());
  chunks.push(managedSection);
  if (after.trim()) chunks.push(after.trim());

  return chunks.join("\n\n") + "\n";
}

export function extractManagedBody(content, markerSet) {
  if (!content) return null;
  const startTag = markerSet?.start || MANAGED_START;
  const endTag = markerSet?.end || MANAGED_END;
  const start = content.indexOf(startTag);
  const end = content.indexOf(endTag);
  if (start === -1 || end === -1 || end < start) return null;
  return content.slice(start + startTag.length, end).trim();
}

export { TOML_MANAGED_START, TOML_MANAGED_END, TOML_MANAGED_BANNER, mergeTomlManaged };
